### ISSUE TITLE
after last merge we got Cannot find module './iframe-action.coffee'

### ISSUE THREAD

**Issue by mdef** [Oitzu/pimatic-iframe#4]
file is simply absent in merge.

**Comment by pimagical** [comment]
Same issue here

**Comment by Oitzu** [comment]
My fault, hadn't the time yesterday to test...
I don't have the time right now, too.
But nevertheless i released 0.1.1 in hope to fix this.

**Comment by mwittig** [comment]
Works for me! Just tested with new the release v0.1.1

**Comment by mdef** [comment]
Works for me too.
