### ISSUE TITLE
iframe size with percentage

### ISSUE THREAD

**Issue by thost96** [Oitzu/pimatic-iframe#7]
Hey, it would be nice to use percentage values for height and width on the iframe device. For example to use the whole width of the parent element. It would make it more comfortable for mobile devices.

**Comment by leader21** [comment]
from the forum https://forum.pimatic.org/topic/2406/iframe-on-mobile/

**Comment by Timvdv** [comment]
Maybe this will help: http://blog.apps.npr.org/pym.js/

**Comment by mwittig** [comment]
@Timvdv thanks for the pointer! Looks promising to me. 

Would you like to take the initiative on this one and trial it on a pimatic-iframe fork?

**Comment by Timvdv** [comment]
@mwittig actually not using the plugin myself, came across this while researching something similar for work.

**Comment by thost96** [comment]
@mwittig I will take a look at it ;)  @Timvdv thanks for the hint!

**Comment by thost96** [comment]
I added a pull request du implement the width and height in percentage.  #12

**Comment by Oitzu** [comment]
Pr #12 is merged into branch "percentage-support" but not working as expected. (aka i fucked up)

**Comment by acefed** [comment]
iframe percentage width was implemented in v0.3.0 yesterday with PR #14
